version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortcut
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - vd_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortcut
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - DATASOURCE_DRIVER=org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  vd_data: